In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('heart_failure_clinical_records_dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[7.500e+01 0.000e+00 5.820e+02 ... 1.000e+00 0.000e+00 4.000e+00]
 [5.500e+01 0.000e+00 7.861e+03 ... 1.000e+00 0.000e+00 6.000e+00]
 [6.500e+01 0.000e+00 1.460e+02 ... 1.000e+00 1.000e+00 7.000e+00]
 ...
 [4.500e+01 0.000e+00 2.060e+03 ... 0.000e+00 0.000e+00 2.780e+02]
 [4.500e+01 0.000e+00 2.413e+03 ... 1.000e+00 1.000e+00 2.800e+02]
 [5.000e+01 0.000e+00 1.960e+02 ... 1.000e+00 1.000e+00 2.850e+02]]


In [5]:
print(X)

[[7.500e+01 0.000e+00 5.820e+02 ... 1.000e+00 0.000e+00 4.000e+00]
 [5.500e+01 0.000e+00 7.861e+03 ... 1.000e+00 0.000e+00 6.000e+00]
 [6.500e+01 0.000e+00 1.460e+02 ... 1.000e+00 1.000e+00 7.000e+00]
 ...
 [4.500e+01 0.000e+00 2.060e+03 ... 0.000e+00 0.000e+00 2.780e+02]
 [4.500e+01 0.000e+00 2.413e+03 ... 1.000e+00 1.000e+00 2.800e+02]
 [5.000e+01 0.000e+00 1.960e+02 ... 1.000e+00 1.000e+00 2.850e+02]]


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[-4.69e-02  0.00e+00]
 [ 1.82e-01  0.00e+00]
 [ 5.79e-01  1.00e+00]
 [ 1.10e-01  0.00e+00]
 [ 1.89e-01  0.00e+00]
 [ 2.01e-01  0.00e+00]
 [ 5.41e-01  0.00e+00]
 [ 5.23e-02  0.00e+00]
 [ 8.41e-01  1.00e+00]
 [ 4.17e-01  0.00e+00]
 [ 1.77e-01  0.00e+00]
 [ 5.88e-01  1.00e+00]
 [ 2.34e-01  1.00e+00]
 [ 1.71e-01  1.00e+00]
 [ 5.44e-01  1.00e+00]
 [ 6.60e-01  1.00e+00]
 [-8.23e-02  0.00e+00]
 [ 3.88e-01  0.00e+00]
 [ 7.64e-02  0.00e+00]
 [ 9.51e-04  0.00e+00]
 [ 4.05e-01  0.00e+00]
 [ 5.15e-01  0.00e+00]
 [ 5.12e-01  1.00e+00]
 [ 4.41e-01  0.00e+00]
 [ 3.82e-01  1.00e+00]
 [ 1.70e-01  0.00e+00]
 [ 2.20e-01  1.00e+00]
 [-9.33e-02  0.00e+00]
 [-1.59e-01  0.00e+00]
 [ 1.07e-01  0.00e+00]
 [ 1.31e-01  0.00e+00]
 [ 6.67e-01  1.00e+00]
 [ 4.14e-01  1.00e+00]
 [ 4.06e-01  0.00e+00]
 [ 2.63e-01  1.00e+00]
 [ 4.23e-01  1.00e+00]
 [ 2.78e-01  0.00e+00]
 [ 3.94e-01  1.00e+00]
 [-2.91e-01  0.00e+00]
 [ 7.76e-01  1.00e+00]
 [-1.47e-01  0.00e+00]
 [ 4.06e-01  0.00e+00]
 [ 3.23e-01  0.00e+00]
 [ 4.16e-01

In [9]:
print(y_pred)

[-0.05  0.18  0.58  0.11  0.19  0.2   0.54  0.05  0.84  0.42  0.18  0.59
  0.23  0.17  0.54  0.66 -0.08  0.39  0.08  0.    0.41  0.51  0.51  0.44
  0.38  0.17  0.22 -0.09 -0.16  0.11  0.13  0.67  0.41  0.41  0.26  0.42
  0.28  0.39 -0.29  0.78 -0.15  0.41  0.32  0.42  0.82  0.32 -0.09  0.
  0.42  0.56  0.37 -0.07  0.27  0.29  0.72  0.27  0.34  0.73 -0.01  0.36]


In [10]:
print("Mean squared error: %.2f" % np.mean((regressor.predict(X_test) - y_test) ** 2))

Mean squared error: 0.15


In [13]:
y_pred=np.where(y_pred > 0.5, 1, 0)

In [14]:
print(y_pred)

[0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0]


In [15]:
print("Mean squared error: %.2f" % np.mean((regressor.predict(X_test) - y_test) ** 2))

Mean squared error: 0.15


In [16]:
print(y_test)

[0 0 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 1 0 1 1 0
 1 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 1 1 0 1 0 0]


In [19]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7833333333333333

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[35,  2],
       [11, 12]], dtype=int64)